### ISSUE TITLE
Assertion failed exception on macOS when cv2 window is in a threaded worker

### ISSUE THREAD

**Issue by sunpazed** [lllyasviel/Fooocus#13]
macOS throws an Assertion failed exception part way through image generation, causing python to crash, as follows;

`Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree),`

This was resolved through monkey patching `cv2win32.py` by adding the window manually `cv2.namedWindow('Foooocus', cv2.WINDOW_NORMAL)`, see gist;

https://gist.github.com/sunpazed/c031307efed3a2be9ee122d2a80e7ea6

**Comment by lllyasviel** [comment]
probably fixed in 1.0.16
https://github.com/lllyasviel/Fooocus/blob/main/update_log.md
launch with "run.bat" to update

**Comment by rickardholmberg** [comment]
Nope, still getting the same error. The call to `modules.cv2win32.show_preview` in `get_previewer()` is still unguarded. It's also seems a bit scary to catch assertions... I also can't get the gist to work, I get this:
```
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/Users/rho/mambaforge/envs/fooocus/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/rho/mambaforge/envs/fooocus/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rho/git/Fooocus/modules/cv2win32.py", line 12, in worker
    cv2.waitKey(50)
cv2.error: Unknown C++ exception from OpenCV code
```

I just removed the calls to `close_all_preview()` and `show_preview()`, and then it works great.
