### ISSUE TITLE
oom kill after long running fooocus with switching models a couple of times

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#698]
I am using v 2.1.675, on Ubuntun 22.04, 32G RAM and 16 VRAM.

After a long run with model switching a couple of times, Fooocus crashed with this sys err log:

```
Oct 16 11:52:27 fqye kernel: [78305.163323] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-3be65058-3077-461c-a878-80309674c641.scope,task=python,pid=788195,uid=1000
Oct 16 11:52:27 fqye kernel: [78305.163470] Out of memory: Killed process 788195 (python) total-vm:58268036kB, anon-rss:28884084kB, file-rss:69552kB, shmem-rss:8832kB, UID:1000 pgtables:73724kB oom_score_adj:0
Oct 16 11:52:27 fqye systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
Oct 16 11:52:27 fqye systemd[3014]: vte-spawn-3be65058-3077-461c-a878-80309674c641.scope: A process of this unit has been killed by the OOM killer.
```

I don't know if model switching is relevant here. Just for your information.

I used to use MRE fork, which seemed to be able to keep running.

@MoonRide303  FYI.

**Comment by MoonRide303** [comment]
@lanyusan I didn't observe this problem on my own machine, so far (v2.1.682 / Windows) but original Fooocus indeed has higher RAM usage when changing base model than MRE (v2.0.78.5 / Windows) - maybe some reference is being held before starting loading new model, or something like that. I will look into it.

**Comment by lanyusan** [comment]
@MoonRide303 
I got a unbuntu PC with 24G vram and tested with a script. It was able to keep on running with model switching.

It looks to be a problem specific for lower vram hardware. The PC with the problem had 16vram.

**Comment by MoonRide303** [comment]
@lanyusan It looks more like RAM than VRAM problem. Could you check how much of memory and swap is available on that machine, for example by using `free -h` command? I'd recommend having at least 20GB of free (mem + swap) before starting Fooocus.

**Comment by lllyasviel** [comment]
there was a mistake in fooocus backend bot. i refreshed it and ram problem should fixed now.

**Comment by MoonRide303** [comment]
@lllyasviel After quick test on my machine (changed base model 3 times) it looks better now (v2.1.694) - RAM usage doesn't peak that high, looks close to (or maybe even lower) than MRE. It's based on rough estimation (I just looked at graphs in Task Manager during generation), but it might be worth introducing numeric peak memory (both RAM & VRAM) usage tracker somewhere in the code. If I remember correctly A1111 displayed that kind of summary after finished generation - maybe something like that (just printed in the log)?

@lanyusan please verify this new version on the machine where problem was originally observed.

**Comment by lanyusan** [comment]
@MoonRide303  

Just tested it. The problem is still there.

Here is `free -h`:

```
               total        used        free      shared  buff/cache   available
Mem:            31Gi       5.5Gi        24Gi       846Mi       1.5Gi        24Gi
Swap:          4.0Gi       4.0Gi       0.0Ki
```

**Comment by MoonRide303** [comment]
@lanyusan that's the old version. Fix was added in v2.1.694.

**Comment by lanyusan** [comment]
@MoonRide303 @lllyasviel 

v2.1.694 kept on running  on a unbutu PC with 16G vram. 

Thanks for the great work. You guys are working at warp speed.

**Comment by MoonRide303** [comment]
@lanyusan This time it was 100% @lllyasviel - but you might want to update and test it again, as I've seen emergency fix related to VRAM usage just landed in v2.1.695 (for Control-LoRA). If it will continue to work fine for you in this new version - feel free to close the issue :).

**Comment by lanyusan** [comment]
@MoonRide303 I indeed ran the testing script on the newest release of 2.1.695. The script calls async worker by randomly picking base model from a pool of 3, refiner model from sdxl and dreamshaper,  and lora model from a pool of 6.

It ran 100 generations with no problem at all. Originally it crashed at around 10 generates.

I think this fix is fine.
