### ISSUE TITLE
Error loading facexlib

### ISSUE THREAD

**Issue by Conasman** [lllyasviel/Fooocus#919]
Hello, 
I've been using Fooocus for a couple days and it's been amazing, no issues before.
Until today, when I launched the "run.bat", and was greeted with the error: 

_Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.38 seconds
Exception in thread Thread-4 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\AI\Fooocus\modules\async_worker.py", line 31, in worker
    import fooocus_extras.face_crop
  File "D:\AI\Fooocus\fooocus_extras\face_crop.py", line 4, in <module>
    import facexlib.utils.face_restoration_helper as face_restoration_helper
ModuleNotFoundError: No module named 'facexlib'._

After this it just stays stuck on Initializing if I try to input a prompt.
Am I missing something ? I haven't changed anything since last time I used it..

Thanks in advance.

**Comment by jepjoo** [comment]
I have the same issue, version 2.1.792. Win 11, 4090.

some more print:

`Collecting filterpy (from facexlib==0.3.0->-r requirements_versions.txt (line 18))
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\eeroi\AppData\Local\Temp\pip-install-57404xo5\filterpy_56199f5cdde04adf9dd47d2ae77629a6\setup.py", line 4, in <module>
      import filterpy
  ModuleNotFoundError: No module named 'filterpy'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

**Comment by pyrowood** [comment]
Same Issue here. Please fix this.

**Comment by rugabunda** [comment]
same problem

**Comment by old-coot** [comment]
same problem

**Comment by lllyasviel** [comment]
2.1.795 fixes this

**Comment by old-coot** [comment]
fixed by turning off the read only checkbox
![image](https://github.com/lllyasviel/Fooocus/assets/134317839/1d91c071-c212-4987-b034-c27dc5f8f640)

**Comment by lllyasviel** [comment]
is it ok now? anyone still having problem?

**Comment by jepjoo** [comment]
> is it ok now? anyone still having problem?

When running Image Prompt -> FaceSwap I still get

`ModuleNotFoundError: No module named 'facexlib'`

Other stuff works though.

**Comment by Conasman** [comment]
> is it ok now? anyone still having problem?

the 2.1.796 fixed it for me, thanks ;)

**Comment by lllyasviel** [comment]
@jepjoo try 2.1.797

**Comment by rugabunda** [comment]
working now tx

**Comment by valan2121** [comment]
hello, what is mean 2.1.795 ?

**Comment by ParOne1** [comment]
what is means 2.1.795?
